"""
AHK命令协议定义
Python和AHK之间的通信命令
"""

# 命令ID定义 (用于WM_COPYDATA的dwData字段)
CMD_PING = 1            # 测试连接
CMD_SET_TARGET = 2      # 设置目标窗口
CMD_ACTIVATE = 3        # 激活目标窗口
CMD_ENQUEUE = 4         # 添加按键到队列
CMD_CLEAR_QUEUE = 5     # 清空队列
CMD_PAUSE = 6           # 暂停队列处理
CMD_RESUME = 7          # 恢复队列处理
CMD_HOOK_REGISTER = 8   # 注册Hook
CMD_HOOK_UNREGISTER = 9 # 取消Hook
CMD_SEND_KEY = 10       # 发送单个按键
CMD_SEND_SEQUENCE = 11  # 发送按键序列
CMD_SET_STATIONARY = 12 # 设置原地模式
CMD_SET_FORCE_MOVE_KEY = 13 # 设置强制移动键
CMD_SET_FORCE_MOVE_STATE = 14 # 设置强制移动状态
CMD_SET_MANAGED_KEY_CONFIG = 15 # 设置管理按键配置
CMD_CLEAR_HOOKS = 16 # 清空所有可配置的Hook
CMD_SET_FORCE_MOVE_REPLACEMENT_KEY = 17 # 设置强制移动替换键
CMD_SET_PYTHON_WINDOW_STATE = 18 # 设置Python窗口状态
CMD_BATCH_UPDATE_CONFIG = 19 # 批量配置更新（Master方案学习）
CMD_SET_SEND_MODE = 20 # 设置发送模式 (direct/control)
CMD_SET_FORCE_MOVE_PASSTHROUGH_KEYS = 21 # 强制移动期间不被替换的白名单键(位移技能)
CMD_SET_MACRO_STEPS = 22  # 设置 AHK 端宏步骤
CMD_START_MACRO = 23      # 启动 AHK 端宏循环
CMD_STOP_MACRO = 24       # 停止 AHK 端宏循环并释放宏持键
CMD_SET_SKILL_HOLD_KEYS = 25  # 声明式设置 TriggerMode=2 期望持键集合(空=全部释放)
CMD_SET_ACCEPTING_ACTIONS = 26  # 运行时闸门:false=原子停止屏障,清场并封住所有输入生产路径(安全清理命令仍放行)
CMD_SHUTDOWN = 27  # 优雅关闭:AHK 自行释放所有持键后退出(terminate 不触发 OnExit)

# 命令名称映射（用于调试）
CMD_NAMES = {
    CMD_PING: "PING",
    CMD_SET_TARGET: "SET_TARGET",
    CMD_ACTIVATE: "ACTIVATE",
    CMD_ENQUEUE: "ENQUEUE",
    CMD_CLEAR_QUEUE: "CLEAR_QUEUE",
    CMD_PAUSE: "PAUSE",
    CMD_RESUME: "RESUME",
    CMD_HOOK_REGISTER: "HOOK_REGISTER",
    CMD_HOOK_UNREGISTER: "HOOK_UNREGISTER",
    CMD_SEND_KEY: "SEND_KEY",
    CMD_SEND_SEQUENCE: "SEND_SEQUENCE",
    CMD_SET_STATIONARY: "SET_STATIONARY",
    CMD_SET_FORCE_MOVE_KEY: "SET_FORCE_MOVE_KEY",
    CMD_SET_FORCE_MOVE_STATE: "SET_FORCE_MOVE_STATE",
    CMD_SET_MANAGED_KEY_CONFIG: "SET_MANAGED_KEY_CONFIG",
    CMD_CLEAR_HOOKS: "CLEAR_HOOKS",
    CMD_SET_FORCE_MOVE_REPLACEMENT_KEY: "SET_FORCE_MOVE_REPLACEMENT_KEY",
    CMD_SET_PYTHON_WINDOW_STATE: "SET_PYTHON_WINDOW_STATE",
    CMD_BATCH_UPDATE_CONFIG: "BATCH_UPDATE_CONFIG",
    CMD_SET_SEND_MODE: "SET_SEND_MODE",
    CMD_SET_FORCE_MOVE_PASSTHROUGH_KEYS: "SET_FORCE_MOVE_PASSTHROUGH_KEYS",
    CMD_SET_MACRO_STEPS: "SET_MACRO_STEPS",
    CMD_START_MACRO: "START_MACRO",
    CMD_STOP_MACRO: "STOP_MACRO",
    CMD_SET_SKILL_HOLD_KEYS: "SET_SKILL_HOLD_KEYS",
    CMD_SET_ACCEPTING_ACTIONS: "SET_ACCEPTING_ACTIONS",
    CMD_SHUTDOWN: "SHUTDOWN",
}

def get_command_name(cmd_id: int) -> str:
    """获取命令名称"""
    return CMD_NAMES.get(cmd_id, f"UNKNOWN({cmd_id})")
